//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranserApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string userID { get; set; }
        public string accountID { get; set; }
        public string accountName { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
