//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranserApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string transactionID { get; set; }
        public string type { get; set; }
        public string fromUserID { get; set; }
        public string toAccID { get; set; }
        public Nullable<decimal> amout { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string status { get; set; }
    }
}
